### PR TITLE
Fix permissions & cleanup boolean logic

### PR DESCRIPTION
**Pull request by TechnicallyCoded**

### CODE REVIEW

**Comment by TechnicallyCoded** [comment]
@XZot1K The merge you did deleted all the fixes and left 1 variable refactor. Likely an accident

**Comment by TechnicallyCoded** [comment]
image

**Comment by XZot1K** [comment]
> image

Yeah looked like another user's pull request tampered with it. I took both pull requests and handled them directly to apply your changes alongside add the simpleportals.admin that was put in by the other guy!

**Comment by TechnicallyCoded** [comment]
> > image
> 
> Yeah looked like another user's pull request tampered with it. I took both pull requests and handled them directly to apply your changes alongside add the simpleportals.admin that was put in by the other guy!

Yes, however, the main fix I was looking to implement wasn't kept.

**Comment by TechnicallyCoded** [comment]
Do you have a way of re-opening this, or should I remake the PR?

**Pull request merged**
